spring.application.name=ti9-backend

server.port=8080

spring.datasource.url = jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres
spring.datasource.username=${USER}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-plataform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show_sql=true

server.servlet.context-path=/dev/api/v1

api.security.token.secret=${JWT_SECRET:my-secret-key}

springdoc.swagger-ui.show-common-extensions=true
