spring.application.name=ti9-backend

server.port=8081

spring.datasource.url = jdbc:postgresql://${host}:${port}/postgres
spring.datasource.username=${usuario}
spring.datasource.password=${senha}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-plataform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.servlet.context-path=/ti9-backend/api/v1

api.security.token.secret=${JWT_SECRET:my-secret-key}

springdoc.swagger-ui.show-common-extensions=true
